Development
ialiev685/goit-markup-hw-05 pull request #1
Opened 2021-01-23 09:24 UTC by ialiev685

Добрый день! Прошу проверить ДЗ № 5.

2021-01-23 10:11 UTC, magom001 requested changes
При переходе на страницу портфолио видно, как уезжат overlay. Так не должно быть. Нужно сделать так, чтобы он изначально был спрятан и появлялся только на hover.

2021-01-23 10:11 UTC, magom001 commented on css/style.css
> +  --transition-color: color 250ms cubic-bezier(0.4, 0, 0.2, 1);
не самый лучший подход: лучше унести в переменные только то, что не меняется

2021-01-23 11:23 UTC, ialiev685 commented on css/style.css
> +  --transition-color: color 250ms cubic-bezier(0.4, 0, 0.2, 1);
Исправил

2021-01-23 11:24 UTC, ialiev685 commented
> При переходе на страницу портфолио видно, как уезжат overlay. Так не должно быть. Нужно сделать так, чтобы он изначально был спрятан и появлялся только на hover.

Исправил

2021-01-26 07:08 UTC, magom001 approved these changes

2021-01-26 19:33 UTC, merged